// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package packets

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AssignT struct {
}

func (t *AssignT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	AssignStart(builder)
	return AssignEnd(builder)
}

func (rcv *Assign) UnPackTo(t *AssignT) {
}

func (rcv *Assign) UnPack() *AssignT {
	if rcv == nil { return nil }
	t := &AssignT{}
	rcv.UnPackTo(t)
	return t
}

type Assign struct {
	_tab flatbuffers.Table
}

func GetRootAsAssign(buf []byte, offset flatbuffers.UOffsetT) *Assign {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Assign{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsAssign(buf []byte, offset flatbuffers.UOffsetT) *Assign {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Assign{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Assign) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Assign) Table() flatbuffers.Table {
	return rcv._tab
}

func AssignStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func AssignEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
