// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package packets

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type BannerT struct {
	Hostname string
	Identifier []int8
}

func (t *BannerT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	hostnameOffset := builder.CreateString(t.Hostname)
	identifierOffset := flatbuffers.UOffsetT(0)
	if t.Identifier != nil {
		identifierLength := len(t.Identifier)
		BannerStartIdentifierVector(builder, identifierLength)
		for j := identifierLength - 1; j >= 0; j-- {
			builder.PrependInt8(t.Identifier[j])
		}
		identifierOffset = builder.EndVector(identifierLength)
	}
	BannerStart(builder)
	BannerAddHostname(builder, hostnameOffset)
	BannerAddIdentifier(builder, identifierOffset)
	return BannerEnd(builder)
}

func (rcv *Banner) UnPackTo(t *BannerT) {
	t.Hostname = string(rcv.Hostname())
	identifierLength := rcv.IdentifierLength()
	t.Identifier = make([]int8, identifierLength)
	for j := 0; j < identifierLength; j++ {
		t.Identifier[j] = rcv.Identifier(j)
	}
}

func (rcv *Banner) UnPack() *BannerT {
	if rcv == nil { return nil }
	t := &BannerT{}
	rcv.UnPackTo(t)
	return t
}

type Banner struct {
	_tab flatbuffers.Table
}

func GetRootAsBanner(buf []byte, offset flatbuffers.UOffsetT) *Banner {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Banner{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsBanner(buf []byte, offset flatbuffers.UOffsetT) *Banner {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Banner{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Banner) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Banner) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Banner) Hostname() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Banner) Identifier(j int) int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetInt8(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *Banner) IdentifierLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Banner) MutateIdentifier(j int, n int8) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt8(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func BannerStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func BannerAddHostname(builder *flatbuffers.Builder, hostname flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(hostname), 0)
}
func BannerAddIdentifier(builder *flatbuffers.Builder, identifier flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(identifier), 0)
}
func BannerStartIdentifierVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func BannerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
