// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package packets

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FilesT struct {
}

func (t *FilesT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	FilesStart(builder)
	return FilesEnd(builder)
}

func (rcv *Files) UnPackTo(t *FilesT) {
}

func (rcv *Files) UnPack() *FilesT {
	if rcv == nil { return nil }
	t := &FilesT{}
	rcv.UnPackTo(t)
	return t
}

type Files struct {
	_tab flatbuffers.Table
}

func GetRootAsFiles(buf []byte, offset flatbuffers.UOffsetT) *Files {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Files{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsFiles(buf []byte, offset flatbuffers.UOffsetT) *Files {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Files{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Files) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Files) Table() flatbuffers.Table {
	return rcv._tab
}

func FilesStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func FilesEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
