// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package packets

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LogoutT struct {
	In uint64
}

func (t *LogoutT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	LogoutStart(builder)
	LogoutAddIn(builder, t.In)
	return LogoutEnd(builder)
}

func (rcv *Logout) UnPackTo(t *LogoutT) {
	t.In = rcv.In()
}

func (rcv *Logout) UnPack() *LogoutT {
	if rcv == nil { return nil }
	t := &LogoutT{}
	rcv.UnPackTo(t)
	return t
}

type Logout struct {
	_tab flatbuffers.Table
}

func GetRootAsLogout(buf []byte, offset flatbuffers.UOffsetT) *Logout {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Logout{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsLogout(buf []byte, offset flatbuffers.UOffsetT) *Logout {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Logout{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Logout) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Logout) Table() flatbuffers.Table {
	return rcv._tab
}

/// in depicts the time.Duration to wait before logout. Defaults to 5s
func (rcv *Logout) In() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 5000000000
}

/// in depicts the time.Duration to wait before logout. Defaults to 5s
func (rcv *Logout) MutateIn(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func LogoutStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func LogoutAddIn(builder *flatbuffers.Builder, in uint64) {
	builder.PrependUint64Slot(0, in, 5000000000)
}
func LogoutEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
