// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package packets

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PingT struct {
	Hostname string
	Identifier string
}

func (t *PingT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	hostnameOffset := builder.CreateString(t.Hostname)
	identifierOffset := builder.CreateString(t.Identifier)
	PingStart(builder)
	PingAddHostname(builder, hostnameOffset)
	PingAddIdentifier(builder, identifierOffset)
	return PingEnd(builder)
}

func (rcv *Ping) UnPackTo(t *PingT) {
	t.Hostname = string(rcv.Hostname())
	t.Identifier = string(rcv.Identifier())
}

func (rcv *Ping) UnPack() *PingT {
	if rcv == nil { return nil }
	t := &PingT{}
	rcv.UnPackTo(t)
	return t
}

type Ping struct {
	_tab flatbuffers.Table
}

func GetRootAsPing(buf []byte, offset flatbuffers.UOffsetT) *Ping {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Ping{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsPing(buf []byte, offset flatbuffers.UOffsetT) *Ping {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Ping{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Ping) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Ping) Table() flatbuffers.Table {
	return rcv._tab
}

/// hostname is the client's detected hostname
func (rcv *Ping) Hostname() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// hostname is the client's detected hostname
/// identifier is the guid generated by pixie
func (rcv *Ping) Identifier() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// identifier is the guid generated by pixie
func PingStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func PingAddHostname(builder *flatbuffers.Builder, hostname flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(hostname), 0)
}
func PingAddIdentifier(builder *flatbuffers.Builder, identifier flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(identifier), 0)
}
func PingEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
