// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package packets

import "strconv"

type PowerType int8

const (
	PowerTypeunknown  PowerType = 0
	PowerTypelogout   PowerType = 1
	PowerTypeshutdown PowerType = 2
	PowerTypereboot   PowerType = 3
)

var EnumNamesPowerType = map[PowerType]string{
	PowerTypeunknown:  "unknown",
	PowerTypelogout:   "logout",
	PowerTypeshutdown: "shutdown",
	PowerTypereboot:   "reboot",
}

var EnumValuesPowerType = map[string]PowerType{
	"unknown":  PowerTypeunknown,
	"logout":   PowerTypelogout,
	"shutdown": PowerTypeshutdown,
	"reboot":   PowerTypereboot,
}

func (v PowerType) String() string {
	if s, ok := EnumNamesPowerType[v]; ok {
		return s
	}
	return "PowerType(" + strconv.FormatInt(int64(v), 10) + ")"
}
