// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package packets

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ResponseT struct {
	Response *RespT
	Time uint64
}

func (t *ResponseT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	responseOffset := t.Response.Pack(builder)
	
	ResponseStart(builder)
	if t.Response != nil {
		ResponseAddResponseType(builder, t.Response.Type)
	}
	ResponseAddResponse(builder, responseOffset)
	ResponseAddTime(builder, t.Time)
	return ResponseEnd(builder)
}

func (rcv *Response) UnPackTo(t *ResponseT) {
	responseTable := flatbuffers.Table{}
	if rcv.Response(&responseTable) {
		t.Response = rcv.ResponseType().UnPack(responseTable)
	}
	t.Time = rcv.Time()
}

func (rcv *Response) UnPack() *ResponseT {
	if rcv == nil { return nil }
	t := &ResponseT{}
	rcv.UnPackTo(t)
	return t
}

type Response struct {
	_tab flatbuffers.Table
}

func GetRootAsResponse(buf []byte, offset flatbuffers.UOffsetT) *Response {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Response{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsResponse(buf []byte, offset flatbuffers.UOffsetT) *Response {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Response{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Response) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Response) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Response) ResponseType() Resp {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return Resp(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Response) MutateResponseType(n Resp) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *Response) Response(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func (rcv *Response) Time() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Response) MutateTime(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func ResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func ResponseAddResponseType(builder *flatbuffers.Builder, responseType Resp) {
	builder.PrependByteSlot(0, byte(responseType), 0)
}
func ResponseAddResponse(builder *flatbuffers.Builder, response flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(response), 0)
}
func ResponseAddTime(builder *flatbuffers.Builder, time uint64) {
	builder.PrependUint64Slot(2, time, 0)
}
func ResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
