// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package packets

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ShowWindowT struct {
}

func (t *ShowWindowT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	ShowWindowStart(builder)
	return ShowWindowEnd(builder)
}

func (rcv *ShowWindow) UnPackTo(t *ShowWindowT) {
}

func (rcv *ShowWindow) UnPack() *ShowWindowT {
	if rcv == nil { return nil }
	t := &ShowWindowT{}
	rcv.UnPackTo(t)
	return t
}

type ShowWindow struct {
	_tab flatbuffers.Table
}

func GetRootAsShowWindow(buf []byte, offset flatbuffers.UOffsetT) *ShowWindow {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ShowWindow{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsShowWindow(buf []byte, offset flatbuffers.UOffsetT) *ShowWindow {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ShowWindow{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ShowWindow) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ShowWindow) Table() flatbuffers.Table {
	return rcv._tab
}

func ShowWindowStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func ShowWindowEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
