// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package packets

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ShutdownT struct {
	In uint64
}

func (t *ShutdownT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	ShutdownStart(builder)
	ShutdownAddIn(builder, t.In)
	return ShutdownEnd(builder)
}

func (rcv *Shutdown) UnPackTo(t *ShutdownT) {
	t.In = rcv.In()
}

func (rcv *Shutdown) UnPack() *ShutdownT {
	if rcv == nil { return nil }
	t := &ShutdownT{}
	rcv.UnPackTo(t)
	return t
}

type Shutdown struct {
	_tab flatbuffers.Table
}

func GetRootAsShutdown(buf []byte, offset flatbuffers.UOffsetT) *Shutdown {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Shutdown{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsShutdown(buf []byte, offset flatbuffers.UOffsetT) *Shutdown {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Shutdown{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Shutdown) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Shutdown) Table() flatbuffers.Table {
	return rcv._tab
}

/// in depicts the time.Duration to wait before shutdown. Defaults to 5s
func (rcv *Shutdown) In() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 5000000000
}

/// in depicts the time.Duration to wait before shutdown. Defaults to 5s
func (rcv *Shutdown) MutateIn(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func ShutdownStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ShutdownAddIn(builder *flatbuffers.Builder, in uint64) {
	builder.PrependUint64Slot(0, in, 5000000000)
}
func ShutdownEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
