---
# Not secure, correct is signed-by
- name: Setup custom repos (GPG)
  become: true
  copy:
    src: "{{ item }}.gpg"
    dest: "/etc/apt/trusted.gpg.d/{{ item }}.gpg"
    mode: 0644
    owner: root
    group: root
  tags: never, repo
  notify: Update APT cache
  loop:
    - icpc
    - vscode
    - atom

- name: Alter security ICPC repo
  become: true
  copy:
    dest: /etc/apt/apt.conf.d/80ssl-exceptions
    src: 80ssl-exceptions
    mode: 0644
    owner: root
    group: root
  tags: never, repo
  notify: Update APT cache

- name: Setup PPA repos (APT)
  become: true
  copy:
    dest: /etc/apt/sources.list.d/customppa.list
    src: pparepos
    mode: 0644
    owner: root
    group: root
  tags: never, repo
  notify: Update APT cache

- name: Refresh caches
  ansible.builtin.meta: flush_handlers
